
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest0 {

  public static boolean debug = false;

  @Test
  public void test1() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test1"); }

    source.org.jfree.chart.JFreeChart jFreeChart1 = null;
    // The following exception was thrown during execution in test generation
    try {
    source.org.jfree.chart.ChartFrame chartFrame3 = new source.org.jfree.chart.ChartFrame("hi!", jFreeChart1, true);
      org.junit.Assert.fail("Expected exception of type java.lang.Error");
    } catch (java.lang.Error e) {
      // Expected exception.
    }

  }

  @Test
  public void test2() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test2"); }

    source.org.jfree.chart.JFreeChart jFreeChart1 = null;
    // The following exception was thrown during execution in test generation
    try {
    source.org.jfree.chart.ChartFrame chartFrame2 = new source.org.jfree.chart.ChartFrame("hi!", jFreeChart1);
      org.junit.Assert.fail("Expected exception of type java.lang.Error");
    } catch (java.lang.Error e) {
      // Expected exception.
    }

  }

  @Test
  public void test3() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test3"); }

    source.org.jfree.chart.JFreeChart jFreeChart1 = null;
    // The following exception was thrown during execution in test generation
    try {
    source.org.jfree.chart.ChartFrame chartFrame3 = new source.org.jfree.chart.ChartFrame("", jFreeChart1, true);
      org.junit.Assert.fail("Expected exception of type java.lang.Error");
    } catch (java.lang.Error e) {
      // Expected exception.
    }

  }

  @Test
  public void test4() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test4"); }

    source.org.jfree.chart.JFreeChart jFreeChart1 = null;
    // The following exception was thrown during execution in test generation
    try {
    source.org.jfree.chart.ChartFrame chartFrame3 = new source.org.jfree.chart.ChartFrame("hi!", jFreeChart1, false);
      org.junit.Assert.fail("Expected exception of type java.lang.Error");
    } catch (java.lang.Error e) {
      // Expected exception.
    }

  }

  @Test
  public void test5() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test5"); }

    source.org.jfree.chart.JFreeChart jFreeChart1 = null;
    // The following exception was thrown during execution in test generation
    try {
    source.org.jfree.chart.ChartFrame chartFrame2 = new source.org.jfree.chart.ChartFrame("", jFreeChart1);
      org.junit.Assert.fail("Expected exception of type java.lang.Error");
    } catch (java.lang.Error e) {
      // Expected exception.
    }

  }

  @Test
  public void test6() throws Throwable {

    if (debug) { System.out.format("%n%s%n","RegressionTest0.test6"); }

    source.org.jfree.chart.JFreeChart jFreeChart1 = null;
    // The following exception was thrown during execution in test generation
    try {
    source.org.jfree.chart.ChartFrame chartFrame3 = new source.org.jfree.chart.ChartFrame("", jFreeChart1, false);
      org.junit.Assert.fail("Expected exception of type java.lang.Error");
    } catch (java.lang.Error e) {
      // Expected exception.
    }

  }

}
